name: Create release from version tag

on:
  push:
    tags:
      - "*"

jobs:
  build_test:
    name: Build and test package
    uses: ./.github/workflows/build-test.yml

  create-release:
    name: Create the release
    runs-on: ubuntu-latest
    needs:
      - build_test
    steps:
      - name: Install dependencies
        run: pip install dunamai

      - name: Check if tag name is PEP-440 compliant
        id: is_pep440_tag_name
        continue-on-error: true
        run: dunamai check --style pep440 $(echo $GITHUB_REF_NAME | sed 's/^v//')

      - name: Determine if package is pre-release
        id: is_prerelease
        continue-on-error: true
        run: python -c "import packaging.version; import sys; sys.exit(1) if not packaging.version.parse(sys.argv[1]).is_prerelease else sys.exit()" $GITHUB_REF_NAME

      - name: Determine if package is post-release
        id: is_postrelease
        continue-on-error: true
        run: python -c "import packaging.version; import sys; sys.exit(1) if not packaging.version.parse(sys.argv[1]).is_postrelease else sys.exit()" $GITHUB_REF_NAME

      - name: Fetch package artifact
        id: download
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build_test.outputs.artifact_name }}

      - name: Set artifact location
        id: artifact_fqfn
        run: echo "artifact_path=$(readlink -f $(ls ${{ steps.download.outputs.download-path }}))" >> $GITHUB_OUTPUT

      - name: Create release
        if: ${{ steps.is_pep440_tag_name.outcome == 'success' && steps.is_postrelease.outcome != 'success' }}
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ steps.artifact_fqfn.outputs.artifact_path }}
          prerelease: ${{ steps.is_prerelease.outcome == 'success' }}
          tag_name: ${{ env.GITHUB_REF_NAME }}
