name: Create release from version tag

on:
  push:
    tags:
      - "*"

jobs:
  build-test:
    name: Build and test package
    uses: ./.github/workflows/build-test.yml

  create-release:
    name: Create the release
    runs-on: ubuntu-latest
    needs:
      - build-test
    steps:
      - name: Install dependencies
        run: pip install dunamai

      - name: Get tag name
        id: tag_name
        continue-on-error: true
        run: dunamai check --style pep440 $(echo $GITHUB_REF_NAME | sed 's/^v//')

      - name: Fetch package artifact
        id: download
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.build-test.outputs.artifact_name }}

      - name: List download path and files
        run: |
          echo "${{ steps.download.outputs.download-path }}"
          echo "$(ls ${{ steps.download.outputs.download-path }})"

      - name: Set artifact location
        id: artifact_fqfn
        run: echo "artifact_path=$(readlink -f $(ls ${{ steps.download.outputs.download-path }}))" >> $GITHUB_OUTPUT

      - name: Display artifact fqfn
        run echo "${{ steps.artifact_fqfn.outputs.artifact_path }}"

      - name: Create release
        if: ${{ steps.tag_name.outcome == 'success' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.GITHUB_REF_NAME }}
          files: ${{ steps.artifact_fqfn.outputs.artifact_path }}
